### ISSUE TITLE
PHP warning when Polygon is created from invalid data.

### ISSUE THREAD

**Issue by munkie** [jmikola/geojson#18]
When not correct data is used to create Polygon following php warning is shown
```php
new \GeoJson\Geometry\Polygon([[2,4]]);

PHP Warning:  array_map(): An error occurred while invoking the map callback in ...
```

I suggest removing array_map in Polygon constructor in favor of using foreach to create coordinates array for polygon.

See php bug related to throwing Exception in array_map callback - https://bugs.php.net/bug.php?id=55416

**Comment by munkie** [comment]
@jmikola Do you want me to create pull request resolving this issue?

**Comment by jmikola** [comment]
@munkie: That would be much appreciated!

**Comment by munkie** [comment]
@jmikola Create PR #19

**Comment by jmikola** [comment]
#19 is merged.

**Comment by munkie** [comment]
:+1:
