### ISSUE TITLE
PHP 8.1: Return type of GeoJson\GeoJson::jsonSerialize()

### ISSUE THREAD

**Issue by jcrombez** [jmikola/geojson#34]
When using PHP 8.1, i get the following log message :
```
Deprecated: Return type of GeoJson\GeoJson::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
```

I appears all the class extending \JsonSerializable and implementing the "jsonSerializer" method needs their return to be explicitly typed to "mixed" for this deprecation to disappear.

**Comment by jmikola** [comment]
This was fixed by https://github.com/jmikola/geojson/commit/cc4c99083ba79bbbe8b49b484091278059ce03a4, which has yet to be released.

I'd like to incorporate most of https://github.com/jmikola/geojson/pull/33 before tagging 1.1.0, so feel free to use `1.1@dev` in the meantime.

**Comment by jcrombez** [comment]
Nice ! Thank you for your time :)
