### ISSUE TITLE
Invalid properties

### ISSUE THREAD

**Issue by Norda-AD** [jmikola/geojson#46]
According to the [RFC 7946](https://datatracker.ietf.org/doc/html/rfc7946#section-3.2), the properties in a Feature objet must be an array or a null value.

When I provide another value (for instance a string), the value is accepted as-is when using `GeoJson::jsonUnserialize`. I was expecting to receive an `GeoJson\Exception\UnserializationException` exception. Is this sensible to you ?

**Comment by gabplch** [comment]
Nope, I just changed Unserialization Exception from global namespace to the library's

**Comment by Norda-AD** [comment]
I am not sure I understand your answer.

Do you mean it makes no sense to throw the UnserializationException when the properties are not properly formatted?
Or do you mean it makes no sense to throw the UnserializationException when there is GeoJson\Exception\UnserializationException ?

If it’s the later, I think my explanation was lousy. I will change my issue.

Regards

Le 2 mai 2024 à 11:04, Vlad Yarysh ***@***.***> a écrit :



Nope, I just changed Unserialization Exception from global namespace to the library's

**Comment by gabplch** [comment]
Sorry, made wrong answer

**Comment by jmikola** [comment]
@Norda-AD: Can you share a failing test case or [MRE](https://en.wikipedia.org/wiki/Minimal_reproducible_example)?

The existing `GeoJson::jsonUnserialize` method does validate that `geometry` and `properties` are either arrays or objects, so I would expect an exception in this case. See: https://github.com/jmikola/geojson/blob/1.2.0/src/GeoJson.php#L117

**Comment by Norda-AD** [comment]
Sorry for the trouble. Indeed, it triggers the error. I don't know why I didn't have that error before.
Maybe it's lost in the many layers of my application.

Thank you for your time.
